---

###############################################################################
# Check role requirements.
- name: Ensure ansible version requirement is fulfilled.
  fail: msg='We need bug fixes in Ansible 2. Please update your kit. "pip install -U Ansible"'
  when: ansible_version.major < 2
  tags:
    - plone
    - plone_backup
    - plone_buildout
    - plone_clients
    - plone_database
    - plone_directories
    - plone_permissions
    - plone_users
    - plone_venv
    - plone_supervisor

- name: Ensure the initial password for Plone is set.
  fail: msg='You must set the plone_initial_password variable.'
  when: not plone_initial_password
  tags:
    - plone
    - plone_backup
    - plone_buildout
    - plone_clients
    - plone_database
    - plone_directories
    - plone_permissions
    - plone_users
    - plone_venv
    - plone_supervisor


###############################################################################
# Check for OS dependencies.
- name: Include OS specific tasks.
  include: 'OS_{{ ansible_os_family }}.yml'
  tags:
    - plone


###############################################################################
# Prepare system setup.
- name: Include setup tasks.
  include: 'setup.yml'


###############################################################################
# Prepare Plone installation.
- name: Include Plone buildout tasks.
  include: 'buildout.yml'


###############################################################################
# Prepare Supervisor management.
- name: Include supervisor management tasks.
  include: 'supervisor.yml'
  tags:
    - plone
    - plone_supervisor
