---

###############################################################################
# Set local facts.
- name: Set convenience variables.
  set_fact:
    supervisor_instance_discriminator: '{{ "%s_" % plone_instance_name }}'


###############################################################################
# Configure supervisor management.
- name: Get supervisor systemctl status.
  shell: systemctl is-enabled supervisor.service
  register: supervisor_service
  when: plone_use_supervisor and ansible_distribution_release == 'xenial'
  changed_when: false
  failed_when: supervisor_service.stderr != ''

- name: Ensure supervisor is started.
  when: plone_use_supervisor
  service:
    name: supervisor
    state: started
    enabled: true

# As of 2016-04-12, Xenial is not getting enabled by service play above
- name: Set supervisor to start on boot in Ubuntu 16.04 Xenial.
  when: plone_use_supervisor and ansible_distribution_release == 'xenial' and supervisor_service.stdout != "enabled"
  shell: systemctl enable supervisor.service


###############################################################################
# Supervisor setup.
- name: Ensure superlance is installed.
  when: plone_use_supervisor
  pip:
    name: superlance
    version: '{{ plone_superlance_version }}'

- name: Ensure supervisor process control setup is done.
  when: plone_use_supervisor and ansible_os_family == 'Debian'
  template:
    src: supervisor_task.j2
    dest: '{{ supervisor_config_dir }}/plone_{{ supervisor_instance_discriminator }}supervisor.conf'
    owner: root
    group: root
    mode: 644
  register: supervisor_task_conf_debian
  notify:
    - restart plone memory monitor

- name: Ensure supervisor task list is updated.
  when: plone_use_supervisor and supervisor_task_conf_debian | changed
  shell: '/bin/kill -HUP `supervisorctl pid`'
  register: supervisord_bounced

- name: Pause if supervisord was restarted.
  when: supervisord_bounced.changed
  pause: minutes=1

- name: Ensure supervisor zeoserver task is started
  when: plone_use_supervisor and plone_install_zeoserver
  supervisorctl:
    name: '{{ supervisor_instance_discriminator }}zeoserver'
    state: started

- name: Ensure supervisor client tasks are started.
  when: plone_use_supervisor
  supervisorctl:
    name: '{{ supervisor_instance_discriminator }}clients:{{ supervisor_instance_discriminator }}client{{ item }}'
    state: started
  with_sequence: count={{ plone_client_count }}

- name: Ensure supervisor client memory monitor is started.
  when: plone_use_supervisor and plone_client_max_memory != "0"
  supervisorctl:
    name: '{{ supervisor_instance_discriminator }}memmon'
    state: started
